In [1]:
import torch
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader, TensorDataset
import pandas as pd
import math
# torch.set_printoptions({'float': '{: 0.8f}'.format})
torch.set_printoptions(sci_mode=False, precision=8)


Load df with y_col

In [2]:
df = pd.read_csv("./footballData/CombinedSlidingWindow4.csv", index_col=False, low_memory=False)
y_col = ['H_Won', 'H_start_odds', 'V_start_odds']
y_df = df[y_col]

# Custom loss function
**Input:** X and Y where each value is between -1 and 1. Both corresponding to the probability of home (+) vs away (-) where 0.5 = 50%, 1.0=100% home chance of winning, -0.7 = 70% visitor chance of winning etc.

Also the odds will be in the input as well

We will use Adam as the optimizer without passing in any. So by default smaller values are

1. Calculate the kelly criterion based on the predicted probability. When it suggests a negative number (no bet) set both X and y to 0
2. Calculate the pearson correlation coefficient, get its absolute value and multiply it by a hyperparameter constant. Combine this with the 



In [29]:
"""
Want: 
    An array > 1 elements for PCC formula
    A smaller array for kelly_criterion
    


x: 1d array of predictions between -1 and 1 where negative number means visitor predicted to win
y: ['H_Won', 'H_start_odds', 'V_start_odds']
pearson_multiplier: constant to multiply the pearson correlation coefficient's result by
max_bet_pct: max percentage allowed per bet.
return_res_array: Skip the torch.cumprod part
"""
def nfl_custom_criterion(x, y, pearson_multiplier=0.5, max_bet_pct=0.1, return_res_array=False):
    # ------------------------------------------------
    # Preliminary calculations
    # ------------------------------------------------
    # acct_value = 100 # Preset account value
    h_start_odds = y[:,1]
    v_start_odds = y[:,2]
    h_won = y[:,0]
    y_decimal_odds = torch.where(x > 0, h_start_odds, v_start_odds) # Decimal odds for model's predicted outcome
    y_prob = 1 / y_decimal_odds                  # Implied Probability (regardless of correct prediction)
    x_H_Won = torch.round(torch.sigmoid(20 * x)) # H_won for predicted bets (Converts model's -1 to 1 range to 0 to 1)
                                                 # Sigmoid so that it's differentiable. The 20 is arbitrarily large number
    y_incorrect_prediction = torch.abs((x_H_Won - h_won))        # 1 if wrong bet, otherwise 0. Used to reset kelly when wrong
    y_incorrect_prediction_mult_two = 2 * y_incorrect_prediction   # 2 if wrong bet, 0 if correct

    #x = torch.abs(x)         # OLD VERSION
    x_prob = torch.where(x > 0, (x + 1) / 2, (1 - x) / 2)
    x = x_prob                # x is now the implied probability(?) of your prediction.
                              # It's a number between 0 and 1 (formerly -1 and 1) representing the model's predicted probability of a win.
                              # This now only shows the probability. Not whether it was correct & not for which side (home vs visitor)

    
    # ------------------------------------------------
    # 1. Calculate the Pearson Correlation Coefficient
    #    Currently includes cases where predicted wrong
    #    ^ This is filtered out after step 2
    # ------------------------------------------------
    n = x.size(0)
    sum_x = torch.sum(x)
    sum_x_squared = torch.sum(x**2)
    sum_y = torch.sum(y_prob)
    sum_y_squared = torch.sum(y_prob**2)
    sum_pow_x = torch.sum(x**2)
    sum_pow_y = torch.sum(y_prob**2)
    x_mul_y = torch.mul(x, y_prob)
    sum_x_mul_y = torch.sum(x_mul_y)

    
    # PCC Formula (eps to avoid NaN)
    eps = 1e-8
    pcc_numerator = n * sum_x_mul_y - sum_x * sum_y
    pcc_denominator_one = torch.sqrt(n * sum_pow_x - sum_x_squared + eps)
    pcc_denominator_two = torch.sqrt(n * sum_pow_y - sum_y_squared + eps)
    pcc = pcc_numerator / (pcc_denominator_one * pcc_denominator_two + eps)
    pcc = pearson_multiplier * torch.abs(pcc)

    
    # ------------------------------------------------
    # 2. Calculate the kelly criterion
    #    Entirely wrong predictions are negated and kept in "incorrect_bets" (pcc not applied to wrong predictions)
    #    Correct predictions are kept in "correct_bets". Pcc is applied to this & stored in pcc_adjusted_correct_bets
    #    Possible issue: This always bets max_bet_pct
    #    The result is cumulatively calculated. i.e. The sum of the previous values are used to calculate the next one
    # ------------------------------------------------
    # kelly_criterion = x - ((1 - x) / y_decimal_odds)  # OLD VERSION
    kelly_criterion = x - ((1 - x) / (y_decimal_odds - 1))
    bet_multiplier = torch.clamp(kelly_criterion, min=0)   # Kelly results that are negative are ignored
    bet_multiplier = bet_multiplier*max_bet_pct            # Scale down the bets to the maximum allowed percentage per bet


    # 4/5/25 adjustment of kelly
    #    Want to use cumprod. Cumsum does nothing and is the same as torch.sum in this scenario?
    #    Basically start with max_bet_pct and return as if you made the bets sequentially
    correct_bet_multiplier = bet_multiplier - (bet_multiplier * y_incorrect_prediction)          # Correct bets after kelly. Bet multiplier or 0
    correct_bet_multiplier = correct_bet_multiplier * (1 - pcc)                                  # "correct_bet_multiplier" penalized by pcc
    print(torch.max(correct_bet_multiplier))
    correct_bet_multiplier = correct_bet_multiplier * y_decimal_odds                             # Bet multiplier taking market odds into account
    incorrect_bet_multiplier = bet_multiplier - (bet_multiplier * y_incorrect_prediction_mult_two) # Negative numbers are incorrect bets
    incorrect_bet_multiplier = torch.clamp(incorrect_bet_multiplier, max=0)                      # Restrict to 0 or negative
    combined_bet_multiplier = correct_bet_multiplier + incorrect_bet_multiplier                  # Combine correct & incorrect bet multipliers
    combined_bet_multiplier = combined_bet_multiplier + 1                                        # Converts to format friendly to cumprod
                                                                                                 # Ex: loss=-0.3, profit=0.3 --> loss=0.7, profit=1.3
    #print(correct_bet_multiplier)
    #print(incorrect_bet_multiplier)
    #print(combined_bet_multiplier)
    # print(pcc)
    
    # ------------------------------------------------
    # Combine & Return
    #     Negate everything for Adam & optuna
    # ------------------------------------------------
    if return_res_array:
        return combined_bet_multiplier
        
    # Prepend max_bet_pct to the tensor before torch.cumprod
    start_bet = torch.tensor([1.0], dtype=torch.float32) # Creates a tensor containing acct_value
    combined_bet_multiplier = torch.cat((start_bet, combined_bet_multiplier))   # Prepends max_bet_pct to the combined_bet_multiplier tensor
    res = -torch.cumprod(combined_bet_multiplier, dim=0)[-1]
    # print(res)
    return res
    # return -torch.cumsum(combined_bets, dim=0)[-1]

In [30]:
x = torch.rand(y_df.shape[0]) * 2 - 1
print(x)
y = torch.tensor(y_df.values, dtype=torch.float32)
n_splits = math.ceil(y_df.shape[0] / 6)

# Split intp batches
BATCH_SIZE = 5
dataset = TensorDataset(x, y)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False)

for id_batch, (x_batch, y_batch) in enumerate(dataloader):
    # print(x_batch.shape)
    # print(y_batch)
    res_df = nfl_custom_criterion(x_batch, y_batch)
    # break
    # print(res_df)
    
#print(y)
# print(y[:,1])
# res_df = nfl_custom_criterion(x,y)
#print(x)
# print(res_df)
# for item in res_df:
#    print(item)

tensor([-0.62665009, -0.02384424,  0.43694627,  ...,  0.87399352,
        -0.04539478,  0.95472026])
tensor(0.08495657)
tensor(0.08521665)
tensor(0.01216520)
tensor(0.07457593)
tensor(0.09415259)
tensor(0.05224717)
tensor(0.06273895)
tensor(0.02658444)
tensor(0.05748691)
tensor(0.07485839)
tensor(0.07491454)
tensor(0.09446795)
tensor(0.07941338)
tensor(0.07774829)
tensor(0.08297612)
tensor(0.)
tensor(0.09491923)
tensor(0.09049226)
tensor(0.05052212)
tensor(0.06448609)
tensor(0.08605917)
tensor(0.09369566)
tensor(0.)
tensor(0.07757268)
tensor(0.09349247)
tensor(0.06040208)
tensor(0.)
tensor(0.02523920)
tensor(1.75049341)
tensor(0.02257928)
tensor(0.08810033)
tensor(0.05425187)
tensor(0.09383181)
tensor(0.09504914)
tensor(0.07821900)
tensor(0.08452503)
tensor(0.04593448)
tensor(0.07419601)
tensor(0.07145416)
tensor(0.07834794)
tensor(0.08342227)
tensor(0.09584946)
tensor(0.09234318)
tensor(0.)
tensor(0.08970167)
tensor(0.06960838)
tensor(0.07695323)
tensor(0.07709125)
tensor(0.05231429)


In [3]:
test_tensor = torch.tensor([100.0000,   0.9000,   1.0981,   0.9000,   0.9353,   1.0000,   1.0981,
                              1.0981,   1.0758,   1.0000,   0.9000,   1.0825,   1.0981,   0.9332,
                              0.9358,   0.9000,   1.0000,   1.0064,   1.0981,   1.0179,   1.0981,
                              1.0981,   1.0639,   1.0840,   0.9000,   1.0981,   1.0981,   1.0934,
                              1.0782,   1.0000,   1.0981,   1.0448,   1.0981,   1.0981,   0.9000,
                              0.9470,   1.0500,   0.9000,   0.9225,   0.9779,   1.0981,   1.0000,
                              1.0977,   1.0014,   1.0832,   1.0000,   1.0000,   1.0670,   1.0319,
                              1.0981,   1.0981,   1.0981,   1.0981,   1.0981,   1.0981,   1.0981,
                              0.9777,   1.0883,   1.0981,   1.0981,   0.9969,   0.9000,   1.0000,
                              1.0237,   1.0094,   1.0665,   1.0569,   0.9310,   1.0656,   0.9110,
                              1.0981,   1.0981,   1.0981,   1.0412,   1.0000,   1.0963,   0.9614,
                              0.9186,   1.0252,   1.0604,   0.9000,   1.0237,   1.0000,   0.9000,
                              1.0981,   0.9000,   1.0981,   1.0000,   1.0157,   1.0807,   1.0408,
                              1.0692,   0.9000,   1.0000,   1.0823,   1.0454,   1.0000,   1.0870,
                              1.0981,   1.0981,   1.0000,   1.0000,   1.0000,   1.0000,   1.0981,
                              1.0981,   1.0000,   0.9616,   1.0000,   1.0000,   1.0981,   1.0981,
                              1.0981,   1.0981,   0.9741,   1.0478,   1.0735,   1.0981,   0.9563,
                              1.0355,   1.0981,   1.0981,   1.0246,   1.0000,   1.0981,   1.0000,
                              0.9377,   1.0000,   0.9736,   1.0449,   0.9000,   1.0000,   1.0770,
                              1.0000,   1.0981,   1.0000,   1.0837,   1.0000,   1.0981,   0.9294,
                              1.0000,   1.0551,   1.0677,   1.0782,   1.0000,   1.0981,   1.0981,
                              1.0652,   1.0981,   1.0432,   0.9995,   1.0981,   1.0000,   1.0981,
                              1.0843,   0.9718,   1.0000,   1.0336,   0.9945,   1.0000,   1.0000,
                              1.0981,   0.9000,   0.9837,   1.0000,   1.0981,   1.0981,   1.0757,
                              1.0981,   1.0014,   1.0672,   0.9000,   1.0981,   1.0981,   0.9000,
                              0.9000,   1.0981,   1.0000,   1.0981,   1.0288,   0.9684,   1.0981,
                              0.9300,   0.9952,   1.0981,   1.0000,   0.9000,   1.0000,   1.0981,
                              0.9000,   1.0981,   0.9775], dtype=torch.float32)

In [5]:
print(torch.cumprod(test_tensor, dim=0))

tensor([  100.00000000,    90.00000000,    98.82899475,    88.94609070,
           83.19127655,    83.19127655,    91.35234070,   100.31399536,
          107.91779327,   107.91779327,    97.12601471,   105.13890839,
          115.45302582,   107.74076080,   100.82380676,    90.74142456,
           90.74142456,    91.32216644,   100.28086853,   102.07589722,
          112.08953857,   123.08551025,   130.95068359,   141.95053101,
          127.75547791,   140.28828430,   154.05055237,   168.43887329,
          181.61079407,   181.61079407,   199.42680359,   208.36112976,
          228.80134583,   251.24674988,   226.12207031,   214.13760376,
          224.84448242,   202.36001587,   186.67712402,   182.55155945,
          200.45986938,   200.45986938,   220.04478455,   220.35285950,
          238.68620300,   238.68620300,   238.68620300,   254.67819214,
          262.80242920,   288.58334351,   316.89334106,   347.98056030,
          382.11743164,   419.60314941,   460.76620483,   505.96

In [6]:
# Generate a tensor with random numbers between -1 and 1
amt_random_numbers = 10
x = torch.rand(amt_random_numbers) * 2 - 1
y = torch.rand(amt_random_numbers) * 2 - 1
# print(type(y))
# print(y.shape)
print(x)
print(y)

nfl_test(x,y)

tensor([-0.38738823, -0.00858855, -0.93326747, -0.30262041, -0.12851167,
         0.99726415, -0.58714378,  0.01136839,  0.43507338,  0.94447637])
tensor([ 0.08781946, -0.13150311,  0.77710104,  0.49798858, -0.76413476,
        -0.15960681, -0.77662611, -0.44353426, -0.09408712, -0.46206462])


NameError: name 'nfl_test' is not defined